/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ETHTickets } from "./ETHTickets"
export * as factories from "./factories"
export { ETHTickets__factory } from "./factories/ETHTickets__factory"
